title: PyTorch Lightning Basic GAN Tutorial
author: PL team
created: 2020-12-21
updated: 2023-03-15
license: CC BY-SA
build: 0
tags:
  - Image
description: |
  How to train a GAN!

  Main takeaways:
  1. Generator and discriminator are arbitrary PyTorch modules.
  2. training_step does both the generator and discriminator training.
requirements:
  - torchvision
  - lightning>=2.0.0rc0
accelerator:
  - CPU
  - GPU
