[tool.black]
# https://github.com/psf/black
line-length = 120
exclude = "(.eggs|.git|.hg|.venv|_build|buck-out|build)"

[tool.isort]
skip_glob = []
profile = "black"
line_length = 120

[tool.autopep8]
ignore = ["E731"]
