title: PyTorch Lightning DataModules
author: PL team
created: 2020-12-21
updated: 2023-03-15
license: CC BY-SA
build: 0
description: This notebook will walk you through how to start using Datamodules. With
  the release of `pytorch-lightning` version 0.9.0, we have included a new class called
  `LightningDataModule` to help you decouple data related hooks from your `LightningModule`.
  The most up-to-date documentation on datamodules can be found
  [here](https://lightning.ai/docs/pytorch/stable/data/datamodule.html).
requirements:
  - torchvision
accelerator:
  - CPU
  - GPU
