title: PyTorch Lightning CIFAR10 ~94% Baseline Tutorial
author: PL team
created: 2020-12-21
updated: 2023-03-15
license: CC BY-SA
build: 0
tags:
  - Image
description: >
  Train a Resnet to 94% accuracy on Cifar10!
requirements:
  - torchvision
  - pandas
  - seaborn
  - lightning>=2.0.0rc0
accelerator:
  - GPU
