# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Enable version updates for python
  - package-ecosystem: "pip"
    # Look for a `requirements` in the `root` directory
    directory: "/_requirements"
    # Check for updates once a week
    schedule:
      interval: "monthly"
    # Labels on pull requests for version updates only
    labels: ["ci/cd"]
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      separator: "-"
    # Allow up to 5 open pull requests for pip dependencies
    open-pull-requests-limit: 5
    reviewers:
      - "Lightning-AI/teams/core-lightning"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels: ["ci/cd"]
    pull-request-branch-name:
      separator: "-"
    open-pull-requests-limit: 5
    reviewers:
      - "Lightning-AI/core-lightning"
