name: Prevent adding/chnaging notebooks

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on PR to master
  pull_request:
    paths:
      - ./**/*.ipynb

jobs:
  block-ipynb:
    runs-on: ubuntu-latest
    steps:
    - run: exit 1
