name: Build Lightning Docs & Deploy to gh-pages

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  make-html:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Make Sphinx documentation for PyTorchLightning
        run: |
          # git config --global --add safe.directory '*'    # to allow sphinx to write to any directory
          ls -alF docs/
          make docs
        continue-on-error: true

      - name: Debug message
        run: |
          ls -alF /tmp
          cat /tmp/*.log
          ls -alF docs/build/html
          pip freeze

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./docs/build/html
          cname: docs.pytorchlightning.kr
          enable_jekyll: false
          force_orphan: true
          user_name: "GitHub Action"
          user_email: "reserve.dev@gmail.com"
          commit_message: "Rebuild w/ ${{ github.event.head_commit.message }}"
          allow_empty_commit: true